<?php
/**
 *Descript:
 *User: jack wang
 *Date: 2020-03-19
 *Time: 22:13
 */

namespace app\admin\controller;

use app\BaseController;
use think\exception\HttpResponseException;


class AdminBase extends BaseController
{
    public $adminUser = null;
    public function initialize()
    {

        parent::initialize(); // TODO: Change the autogenerated stub
        //判断是否登陆
        if(!$this->isLogin()){
            return $this->redirect(url("/login/index"));
        }
    }

    /**
     * 判断是否登陆
     * @return bool
     */
    public function isLogin(){
        $this->adminUser = session(config("admin.admin_session"));

        if(empty($this->adminUser)){

            return false;
        }
        return true;
    }

    public function redirect(...$args){
        throw new HttpResponseException(redirect(...$args));
    }
}