<?php
/**
 *Descript:Api模块的基类控制器
 *User: jack wang
 *Date: 2020-03-23
 *Time: 10:22
 */

namespace app\api\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args){
        throw new HttpResponseException(show(...$args));
    }
}